package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrdernum<M extends BaseOrdernum<M>> extends Model<M> implements IBean {

	public void setServerId(java.lang.Integer serverId) {
		set("server_id", serverId);
	}

	public java.lang.Integer getServerId() {
		return get("server_id");
	}

	public void setOverNum(java.lang.String overNum) {
		set("over_num", overNum);
	}

	public java.lang.String getOverNum() {
		return get("over_num");
	}

}
