package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseServer<M extends BaseServer<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setServerImg(java.lang.String serverImg) {
		set("server_img", serverImg);
	}

	public java.lang.String getServerImg() {
		return get("server_img");
	}

	public void setServerName(java.lang.String serverName) {
		set("server_name", serverName);
	}

	public java.lang.String getServerName() {
		return get("server_name");
	}

	public void setServerType(java.lang.String serverType) {
		set("server_type", serverType);
	}

	public java.lang.String getServerType() {
		return get("server_type");
	}

	public void setServerAddress(java.lang.String serverAddress) {
		set("server_address", serverAddress);
	}

	public java.lang.String getServerAddress() {
		return get("server_address");
	}

	public void setServerTel(java.lang.String serverTel) {
		set("server_tel", serverTel);
	}

	public java.lang.String getServerTel() {
		return get("server_tel");
	}

}
