package com.demo.common.model;

import com.demo.common.model.base.BaseImg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Img extends BaseImg<Img> {
	public static final Img dao = new Img();
}
