package com.demo.common.model;

import com.demo.common.model.base.BaseOrdertab;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ordertab extends BaseOrdertab<Ordertab> {
	public static final Ordertab dao = new Ordertab();
	public Page<Ordertab> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from ordertab order by id asc");
	}
}
