package com.demo.common.model;

import com.demo.common.model.base.BaseOrdernum;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ordernum extends BaseOrdernum<Ordernum> {
	public static final Ordernum dao = new Ordernum();
	public Page<Ordernum> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from ordernum order by server_id asc");
	}
}
