package com.demo.common.model;

import com.demo.common.model.base.BaseScene;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Scene extends BaseScene<Scene> {
	public static final Scene dao = new Scene();
	
	public Page<Scene> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from server order by id asc");
	}
}
