package com.demo.common.model;

import com.demo.common.model.base.BaseServer;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Server extends BaseServer<Server> {
	public static final Server dao = new Server();
	public Page<Server> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from server order by id asc");
	}
}
