package com.demo.common.model;

import com.demo.common.model.base.BaseShop;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Shop extends BaseShop<Shop> {
	public static final Shop dao = new Shop();
	
	public Page<Shop> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from server order by id asc");
	}
}
